"""Curated sources for prompt injection research paper.

Each source is a real, verifiable publication drawn from S02-RESEARCH.md.
Fields: author, year, title, source_type, credibility, url, pillar_tags.
"""

SOURCES = [
    {
        "author": "Abdallah, M., Barreno, A., Bensalah, F., et al.",
        "year": 2025,
        "title": "Prompt Injection Attacks in Large Language Models and AI Agent Systems: A Comprehensive Review",
        "source_type": "academic",
        "credibility": "high",
        "url": "https://www.mdpi.com/2078-2489/17/1/54",
        "pillar_tags": ["taxonomy", "risks", "detection", "prevention"],
    },
    {
        "author": "OWASP Foundation",
        "year": 2025,
        "title": "OWASP Top 10 for Large Language Model Applications",
        "source_type": "industry",
        "credibility": "high",
        "url": "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
        "pillar_tags": ["taxonomy", "risks", "prevention"],
    },
    {
        "author": "National Institute of Standards and Technology",
        "year": 2025,
        "title": "Adversarial Machine Learning: A Taxonomy and Terminology of Attacks and Mitigations (AI 100-2e2025)",
        "source_type": "government",
        "credibility": "high",
        "url": "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-2e2025.pdf",
        "pillar_tags": ["taxonomy", "risks"],
    },
    {
        "author": "Ahmed, S., Kaur, K., & Sharma, R.",
        "year": 2025,
        "title": "Prompt Injection 2.0: Hybrid AI Threats",
        "source_type": "academic",
        "credibility": "high",
        "url": "https://arxiv.org/abs/2507.13169",
        "pillar_tags": ["taxonomy"],
    },
    {
        "author": "Greshake, K., Abdelnabi, S., Mishra, S., Endres, C., Giner, T., & Fritz, M.",
        "year": 2023,
        "title": "Not What You've Signed Up For: Compromising Real-World LLM-Integrated Applications with Indirect Prompt Injection",
        "source_type": "academic",
        "credibility": "high",
        "url": "https://arxiv.org/abs/2302.12173",
        "pillar_tags": ["taxonomy", "risks"],
    },
    {
        "author": "Schulhoff, S., Pinto, J., Khan, A., Bouchard, L.-F., Si, C., Anati, S., & Boyd-Graber, J.",
        "year": 2023,
        "title": "Ignore This Title and HackAPrompt: Exposing Systemic Weaknesses of LLMs through a Global Scale Prompt Hacking Competition",
        "source_type": "academic",
        "credibility": "high",
        "url": "https://arxiv.org/abs/2311.16119",
        "pillar_tags": ["taxonomy", "risks"],
    },
    {
        "author": "CrowdStrike",
        "year": 2024,
        "title": "Prompt Injection: Definition and Attack Taxonomy",
        "source_type": "industry",
        "credibility": "high",
        "url": "https://www.crowdstrike.com/en-us/cybersecurity-101/cyberattacks/prompt-injection/",
        "pillar_tags": ["taxonomy", "risks"],
    },
    {
        "author": "Willison, S.",
        "year": 2024,
        "title": "Prompt Injection series",
        "source_type": "industry",
        "credibility": "high",
        "url": "https://simonwillison.net/series/prompt-injection/",
        "pillar_tags": ["taxonomy", "risks", "detection", "prevention"],
    },
    {
        "author": "Anthropic",
        "year": 2024,
        "title": "Research on AI Safety and Prompt Security",
        "source_type": "industry",
        "credibility": "high",
        "url": "https://www.anthropic.com/research",
        "pillar_tags": ["risks", "prevention"],
    },
    {
        "author": "ProtectAI",
        "year": 2023,
        "title": "Rebuff: Self-Hardening Prompt Injection Detector",
        "source_type": "tool",
        "credibility": "medium",
        "url": "https://github.com/protectai/rebuff",
        "pillar_tags": ["detection"],
    },
    {
        "author": "Alon, G., & Kamfonas, M.",
        "year": 2023,
        "title": "Detecting Language Model Attacks with Perplexity",
        "source_type": "academic",
        "credibility": "high",
        "url": "https://arxiv.org/abs/2308.14132",
        "pillar_tags": ["detection"],
    },
    {
        "author": "Wallace, E., Xiao, K., Leike, J., Weng, L., Heidecke, J., & Beutel, A.",
        "year": 2024,
        "title": "The Instruction Hierarchy: Training LLMs to Prioritize Privileged Instructions",
        "source_type": "academic",
        "credibility": "high",
        "url": "https://arxiv.org/abs/2404.13208",
        "pillar_tags": ["prevention", "detection"],
    },
    {
        "author": "Anthropic",
        "year": 2024,
        "title": "System Prompt Security Best Practices",
        "source_type": "industry",
        "credibility": "high",
        "url": "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/system-prompts",
        "pillar_tags": ["prevention"],
    },
    {
        "author": "NVIDIA",
        "year": 2024,
        "title": "NeMo Guardrails: Programmable Guardrails for LLM Applications",
        "source_type": "tool",
        "credibility": "high",
        "url": "https://github.com/NVIDIA/NeMo-Guardrails",
        "pillar_tags": ["prevention", "detection"],
    },
    {
        "author": "Lakera AI",
        "year": 2024,
        "title": "Lakera Guard: Real-Time Prompt Injection Detection",
        "source_type": "tool",
        "credibility": "medium",
        "url": "https://www.lakera.ai/",
        "pillar_tags": ["detection", "prevention"],
    },
    {
        "author": "Liu, Y., Jia, Y., Geng, R., Jia, J., & Gong, N. Z.",
        "year": 2024,
        "title": "Formalizing and Benchmarking Prompt Injection Attacks and Defenses",
        "source_type": "academic",
        "credibility": "high",
        "url": "https://arxiv.org/abs/2310.12815",
        "pillar_tags": ["taxonomy", "detection", "prevention"],
    },
    {
        "author": "Yi, J., Xie, Y., Zhu, B., Hines, K., Kiciman, E., Sun, G., Xie, X., & Wu, F.",
        "year": 2024,
        "title": "Jailbreak Attacks and Defenses Against Large Language Models: A Survey",
        "source_type": "academic",
        "credibility": "high",
        "url": "https://arxiv.org/abs/2407.04295",
        "pillar_tags": ["taxonomy", "risks", "detection", "prevention"],
    },
    {
        "author": "BSG",
        "year": 2025,
        "title": "OWASP LLM Top 10 (2025) Analysis",
        "source_type": "industry",
        "credibility": "medium",
        "url": "https://bsg.tech/blog/owasp-llm-top-10/",
        "pillar_tags": ["risks", "prevention"],
    },
]
